- name: Bring up monitoring stack
  hosts: monitoring
  become: true
  
  vars:
    docker_users: [ubuntu]
  
  roles:
    - geerlingguy.docker
  
  tasks:
    - name: Create monitoring stack folder
      file:
        path: /opt/monitoring
        state: directory
    - name: Copy prometheus.yaml
      copy:
        src: prometheus.yaml
        dest: /opt/monitoring/prometheus.yaml
    - name: Copy compose.yaml
      copy:
        src: compose.yaml
        dest: /opt/monitoring/compose.yaml
    - name: Bring up container
      command: docker compose up -d
      args:
        chdir: /opt/monitoring