- name: Install Ansible Galaxy packages on all servers
  hosts: all
  become: true
  vars:
    docker_users:
      - ubuntu
      - ssm-user
  roles:
    - name: geerlingguy.docker
  collections:
    - name: amazon.aws
    - name: prometheus.prometheus